name: PullRequest - Terragrunt plan Stage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read


jobs:
  Validate:
    defaults:
      run:
        shell: bash
    outputs:
      GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
      CHINA_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT }}
      validation_empty_array: ${{ steps.aws-target-account-finder.outputs.validation_empty_array }}
    name: "Get changed files from the PullRequest stage"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Select AWS target accounts for planning
        id: aws-target-account-finder
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: /bin/bash .github/scripts/github.sh

      - name: export variable outpuit
        env:
          GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
          CHINA_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT }}
          validation_empty_array: ${{ steps.aws-target-account-finder.outputs.validation_empty_array }}
        run: echo "The selected color is $CHINA_RUNNER_AWS_TAARGET_ACCOUNT $GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT"
      


  terragrunt_plan_global:
    name: "Terragrunt plan Global"
    runs-on: ubuntu-latest
    needs: [Validate]
    if: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT != '' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Plan ${{ matrix.aws_accounts.name }}'
        id: terragrunt_plan
        env:
            GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
        run: |
          echo "Terragrunt plan --bla $GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT"


  terragrunt_plan_china:
    name: "Terragrunt plan China"
    runs-on: ubuntu-latest
    needs: [Validate]
    if: ${{ needs.Validate.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT != '' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Plan ${{ matrix.aws_accounts.name }}'
        id: terragrunt_plan
        env:
            CHINA_RUNNER_AWS_TAARGET_ACCOUNT: ${{ needs.Validate.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT }}
        run: |
          echo "Terragrunt plan --bla $CHINA_RUNNER_AWS_TAARGET_ACCOUNT"

