name: PullRequest - Terragrunt plan Stage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read


jobs:
  Validate:
    defaults:
      run:
        shell: bash
    outputs:
      GLOBAL_RUNNER_AWS_TARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.GLOBAL_RUNNER_AWS_TARGET_ACCOUNT }}
      CHINA_RUNNER_AWS_TARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.CHINA_RUNNER_AWS_TARGET_ACCOUNT }}
      validation_empty_array: ${{ steps.aws-target-account-finder.outputs.validation_empty_array }}
    name: "Get changed files from the PullRequest stage"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # env:
    #   commitmsg: ${{ github.event.head_commit.message }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      # - name: get commit message
      #   run: |
      #       echo Commit MSG = ${{ env.commitmsg }}

      # - name: Print Webhook Events and Payloads
      #   run: |
      #     echo "Webhook Event Name: ${{ github.event_name }}"
      #     echo "Webhook Event Name: ${{ github.event.pull_request.title }}"
      #     echo "Webhook Payload: ${{ toJson(github.event) }}"
      #     echo "Commit Message: ${{ github.event.head_commit.message }}"


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Select AWS target accounts for planning
        id: aws-target-account-finder
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          COMMIT_MESSAGE_TRIGGER: ${{ github.event.pull_request.title }}
        run: /bin/bash .github/scripts/github.sh
      


  terragrunt_plan_global:
    name: "Terragrunt plan Global"
    runs-on: ubuntu-latest
    needs: [Validate]
    if: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TARGET_ACCOUNT != '' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Plan'
        id: terragrunt_plan
        env:
            GLOBAL_RUNNER_AWS_TARGET_ACCOUNT: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TARGET_ACCOUNT }}
        run: /bin/bash .github/scripts/terragrunt_plan.sh "$GLOBAL_RUNNER_AWS_TARGET_ACCOUNT"


  terragrunt_plan_china:
    name: "Terragrunt plan China"
    runs-on: ubuntu-latest
    needs: [Validate]
    if: ${{ needs.Validate.outputs.CHINA_RUNNER_AWS_TARGET_ACCOUNT != '' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Plan'
        id: terragrunt_plan
        env:
            CHINA_RUNNER_AWS_TARGET_ACCOUNT: ${{ needs.Validate.outputs.CHINA_RUNNER_AWS_TARGET_ACCOUNT }}
        run: /bin/bash .github/scripts/terragrunt_plan.sh "$CHINA_RUNNER_AWS_TARGET_ACCOUNT"

