name: PullRequest - Terragrunt plan Stage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read


jobs:
  Validate:
    defaults:
      run:
        shell: bash
    outputs:
      GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
      CHINA_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT }}
      validation_empty_array: ${{ steps.aws-target-account-finder.outputs.validation_empty_array }}
    name: "Get changed files from the PullRequest stage"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and 
        #   the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: Terragrunt Plan Global
        id: aws-target-account-finder
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: /bin/bash .github/scripts/github.sh

      - name: export variable outpuit
        env:
          GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
          CHINA_RUNNER_AWS_TAARGET_ACCOUNT: ${{ steps.aws-target-account-finder.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT }}
          validation_empty_array: ${{ steps.aws-target-account-finder.outputs.validation_empty_array }}
        run: echo "The selected color is $CHINA_RUNNER_AWS_TAARGET_ACCOUNT $GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT"
      

      #trigger_global_pipeline: ${{ steps.aws-target-account-finder.outputs.trigger_china_pipeline }}



  terragrunt_plan_global:
    name: "Terragrunt plan Global"
    runs-on: ubuntu-latest
    needs: [Validate]
    #if: ${{ needs.Validate.outputs.trigger_china == true }}
    if: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT != '' }}
    # if: ${{ needs.Validate.outputs.trigger_china_pipeline == true }}
    # if: ${{ needs.Validate.aws-target-account-finder.outputs.trigger_china_pipeline == 'true' }} 
    # strategy:
      # matrix:
      #   # Iterating through hardcoded dir path and comparing changed file
      #   aws_accounts:
      #     - name: management-global-prod
      #       account_id: 211125582498
      #     - name: network-global-prod
      #       account_id: 471112563910
      #     - name: sharedsvc-global-prod
      #       account_id: 590184046954
      #     - name: monitoring-global-prod
      #       account_id: 905418137412
      #     - name: security-global-prod
      #       account_id: 851725647430

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Plan ${{ matrix.aws_accounts.name }}'
        id: terragrunt_plan
        env:
            GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT: ${{ needs.Validate.outputs.GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT }}
        #if: contains( needs.Validate.outputs.changed_files, matrix.aws_accounts.name )
        run: |
          echo "Terragrunt plan --bla $GLOBAL_RUNNER_AWS_TAARGET_ACCOUNT"


  terragrunt_plan_china:
    name: "Terragrunt plan China"
    runs-on: ubuntu-latest
    needs: [Validate]
    #if: ${{ needs.Validate.outputs.trigger_china == true }}
    if: contains(needs.Validate.outputs.CHINA_RUNNER_AWS_TAARGET_ACCOUNT, 'true')
    # if: ${{ needs.Validate.outputs.trigger_china_pipeline == true }}
    # if: ${{ needs.Validate.aws-target-account-finder.outputs.trigger_china_pipeline == 'true' }} 
    # strategy:
      # matrix:
      #   # Iterating through hardcoded dir path and comparing changed file
      #   aws_accounts:
      #     - name: management-global-prod
      #       account_id: 211125582498
      #     - name: network-global-prod
      #       account_id: 471112563910
      #     - name: sharedsvc-global-prod
      #       account_id: 590184046954
      #     - name: monitoring-global-prod
      #       account_id: 905418137412
      #     - name: security-global-prod
      #       account_id: 851725647430

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Plan ${{ matrix.aws_accounts.name }}'
        id: terragrunt_plan
        env:
            SELECTED_COLOR: ${{ needs.Validate.outputs.trigger_china }}
        #if: contains( needs.Validate.outputs.changed_files, matrix.aws_accounts.name )
        run: |
          echo $SELECTED_COLOR 

  # cleanup:
  #   runs-on: ubuntu-latest
  #   needs: [terragrunt_plan]
  #   steps:
  #   - name: WS cleanup
  #     run: |
  #       sudo rm -rf ${{ github.workspace }}/*