name: PullRequest - Terragrunt plan Stage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

env:
  iam_doer_role_name: "infrastructure-doer-role"
  aws_region: "eu-central-1"

jobs:
  Validate:
    name: "Get changed files from the PullRequest stage"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: Terragrunt Plan
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          JSON_ACC_LIST_PATH: accounts.json
          MODIFIED_FILES_PATH: (a)
        run: |
          function execute_trgrnt () {
            echo "########## Terragrunt Operations ###################"
            echo "terragrunt plan --terragrunt-provider-cache ${MODIFIED_FILES_PATH[@]}"
          }
          for file in ${ALL_CHANGED_FILES}; do
            for aws_account_name in `jq -r 'keys[]' $JSON_ACC_LIST_PATH|grep -v china`; do
              if [[ $file == *"$aws_account_name"* ]]; then
                echo "$file is part of the accound $aws_account_name"
                # MODIFIED_FILES_PATH+=($aws_account_name)
              fi
            done
          echo $MODIFIED_FILES_PATH

            
          done


      # - name: Detect changed files
      #   id: changed_files
      #   uses: dorny/paths-filter@v3
      #   with:
      #     #list-files: 'escape'
      #     list-files: shell
      #     base: 'main'
      #     filters: |
      #       changed:
      #         - '**/*.sh'

      # - name: 'Setup Terraform'
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.1
      #     terraform_wrapper: false

      # - name: 'Setup Terragrunt'
      #   uses: autero1/action-terragrunt@v1.1.0
      #   with:
      #     terragrunt_version:  0.48.0

      # - name: Interact with Terragrunt
      #   run: terragrunt --version

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::288242937299:role/GitHubCI
      #     role-session-name: InfraWriterSession
      #     aws-region: eu-central-1

      - name: Print changed files
        shell: bash
        run: |
          echo "${{ steps.changed_files.outputs.changed }}"

      # Exporting the changed files pipeline level variable intro the environment
      - name: PREPARE ENV VAR
        # env: 
        #   CHANGED_FILES_PR:  ${{ steps.changed_files.outputs.changed_files }}
        shell:  bash
        #run: echo "Yeah boyy $CHANGED_FILES_PR"
        run: |
          git diff --name-only
          export TEST=$(git diff --name-only)
          echo $TEST


  # terragrunt_plan:
  #   name: "Terragrunt plan "
  #   runs-on: ubuntu-latest
  #   needs: [Validate]
  #   # strategy:
  #     # matrix:
  #     #   # Iterating through hardcoded dir path and comparing changed file
  #     #   aws_accounts:
  #     #     - name: management-global-prod
  #     #       account_id: 211125582498
  #     #     - name: network-global-prod
  #     #       account_id: 471112563910
  #     #     - name: sharedsvc-global-prod
  #     #       account_id: 590184046954
  #     #     - name: monitoring-global-prod
  #     #       account_id: 905418137412
  #     #     - name: security-global-prod
  #     #       account_id: 851725647430

  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     - name: 'Plan ${{ matrix.aws_accounts.name }}'
  #       #if: contains( needs.Validate.outputs.changed_files, matrix.aws_accounts.name )
  #       run: |
  #         echo "terragrunt run-all plan --terragrunt-non-interactive" && pwd



  # cleanup:
  #   runs-on: ubuntu-latest
  #   needs: [terragrunt_plan]
  #   steps:
  #   - name: WS cleanup
  #     run: |
  #       sudo rm -rf ${{ github.workspace }}/*