name: Reusable Workflow

on:
  workflow_call:
    inputs:
      aws-target-account:
        required: true
        type: string

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terragrunt Apply
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.1
          terraform_wrapper: false

      - name: 'Setup Terragrunt'
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.48.0

      - name: Interact with Terragrunt
        run: terragrunt --version

      - name: Echo Parameters
        run: |
          echo "Running terraform apply for account/environment: ${{ inputs.aws-target-account }}"

      - name: 'Terragrunt Apply'
        run: |
          echo "terragrunt run-all apply --terragrunt-non-interactive --terragrunt-log-level ${{ inputs.logLevel }}"
        working-directory: ${{ inputs.aws-target-account }}
        if: github.event_name == 'workflow_dispatch'

  cleanup:
    runs-on: ubuntu-latest
    needs: [apply]
    steps:
    - name: WS cleanup
      run: |
        sudo rm -rf ${{ github.workspace }}/*